import { ApolloWrapper } from "@/lib/apollo/client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <nav>
            <Link href={"/"}>Questions</Link>
            <Link href={"/new-question"}>New Question</Link>
          </nav>
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
        </ApolloWrapper>
      </body>
    </html>
  );
}
